### PR TITLE
fix count sql query to use index

### PR DESCRIPTION
**Pull request by dpevunov-cp**

### CODE REVIEW

**Comment by poeti8** [comment]
The develop branch contains Kutt version 2, which no longer is being worked on. Are sure you want to merge this change into the develop branch?
Also, how come `count("*")` is faster than `count("id")`? I tried it with a few millions rows and they were almost equal, with `count("id")` being slightly faster. Did you benchmark this yourself?

**Comment by dpevunov-cp** [comment]
> The develop branch contains Kutt version 2, which no longer is being worked on
I want this fix be published as a patch for version 2 yes. We use this service and this query takes most of the time on the server
> Also, how come count("*") is faster than count("id")
Postgres is able to optimise the query with * just by using an index on the field so no need to traverse the data itself. Have you tested it with index created?

**Comment by poeti8** [comment]
> Have you tested it with index created?

Index for which field? What kind of index are we talking about?

**Comment by dpevunov-cp** [comment]
> > Have you tested it with index created?
> 
> Index for which field? What kind of index are we talking about?

I have tested it the following way. 
I added btree index for id field - it did not work. The query was still using seq scan to count
Then I ran EXPLAIN changing "id" to * and it showed me that now it uses index only scan to count

**Comment by poeti8** [comment]
Weird, when I used EXPLAIN I got the same query plan for both. Anyway, I'll merge this one for the other reason—extra IS NULL check for id—at least.

I'll keep this one in mind to update queries where count is used in the version 3. Thanks.

**Pull request merged**
