### PR TITLE
Added Minimal User Management for Admins

### PR DESCRIPTION
**Pull request by bytepoets-blo**
Hi there!

We just set-up Kutt internally and it works great so far! Thank you for creating this!

In the spirit of giving back, we added a bit of functionality we needed internally, hopefully this is of use to others as well.

Implementation of a minimal user management according to our internal requirements:
- Create a new user (when registration is disabled)
- Ban a user
- Delete a user

These are only available as Admin

Fixes parts of: #157 

We tried to keep the UI consistent. If there are any issues, please let us know.

### CODE REVIEW

**Comment by poeti8** [comment]
Thank you, this looks really nice!

**Comment by poeti8** [comment]
When you visit `/users` directly you're gonna face 404. The solution is to add `users` to `validators.ts` file inside `preservedUrls`

**Comment by poeti8** [comment]
I'd suggest to move the create user button to the outside of the table, and add `+` icon to it. 

image

**Comment by poeti8** [comment]
Create user modal form elements - label, input and button - are a bit too big. Can make them smaller.

**Comment by poeti8** [comment]
Now that we have users, we can show more info on the table as well:
- Domains they own
- Number of links they have created

I'm gonna work on these later after we merged this PR, just throwing the idea here.

**Comment by poeti8** [comment]
Can change the "users" button text in the menu and also the url and route to admin, so it would have a more general purpose.

**Comment by bytepoets-blo** [comment]
Thank you for your feedback and suggestions. Will have a go at implementing them in the next days.

**Comment by poeti8** [comment]
Is this ready? I really want to merge this and then apply some features on top of it.

**Comment by bytepoets-blo** [comment]
Haven't moved the "New User" Button out of the table yet. This would make the refresh logic a bit more complicated, haven't had time to do that yet. If you can live with the button inside the table then you can merge it of course.

**Comment by liukch** [comment]
I really need this feature, but why it was not appeared in the latest version?

**Comment by tiritibambix** [comment]
Would love to see this implemented ! Is it still a thing ?

**Pull request merged**
