### PR TITLE
Support for Optional Headers to Comply with TRAI Regulations

### PR DESCRIPTION
**Pull request by yescay**
### Overview
This pull request introduces support for optional headers in Kutt.it. These headers allow users to include custom metadata when generating short URLs. This enhancement aims to assist organizations in complying with TRAI’s regulations for commercial communications by enabling them to add the necessary identifiers or attributes mandated by the government.

### New Feature:

- Users can now pass optional headers when creating or managing short URLs.
- These headers can store additional optional metadata as sender IDs
- Key Use Case:
- Organizations sending promotional or transactional messages through SMS or emails need to comply with TRAI's guidelines (e.g., DLT compliance).
- By adding the necessary headers, the short URLs generated via Kutt.it can carry the required identifiers or templates without impacting the URL structure or drastically increasing the size.

### Backward Compatibility

- The feature is backward compatible. If no headers are passed, the system behaves as before without any impact on existing functionalities.
- Existing users are not required to change their integration or workflows unless they wish to leverage the new feature.

### Manual tests have been added to verify:
Optional headers are properly accepted and processed.
The absence of headers does not affect URL generation.
a8-shorten-url

### CODE REVIEW

**Comment by yescay** [comment]
Hey team! Just following up on PR #767 that I submitted a few days ago. Let me know if I need to do anything further.

**Comment by poeti8** [comment]
Thanks, but I'm not interested in adding this to the main branch.

**Comment by yescay** [comment]
Thanks for considering.. This is the first ever pull request I have made -
so wonder if you can share the reason for not considering ..

Thanks
Kamesh

**Comment by poeti8** [comment]
@yescay While useful for you, this is not a common use-case for Kutt. Thanks again though.

**Comment by yescay** [comment]
No problem, Thanks for taking the time to explain.

**Pull request closed without merging**
