### PR TITLE
Add the documentation how to configure Kutt

### PR DESCRIPTION
**Pull request by 8sd**

### CODE REVIEW

**Comment by poeti8** [comment]
Why the link to official image on hub is removed?

**Comment by 8sd** [comment]
Are you referring to line 65?

Isn't that an old link to the beta of v2?

**Comment by poeti8** [comment]
No I'm referring to line 75, https://hub.docker.com/r/kutt/kutt

**Comment by 8sd** [comment]
See the edited comment

**Comment by poeti8** [comment]
> But if you like I can add it again :)

Yes please.

**Pull request merged**
