### PR TITLE
fix 24, support getting api-key from header

### PR DESCRIPTION
**Pull request by isayme**

### CODE REVIEW

**Comment by poeti8** [comment]
Great. But I tested it and it didn't work. I tried to debug it and found out that the `passport-localapi` version on NPM is behind its GitHub repository. So basically it does not have the feature to extract the API from the header. Then I found this:
https://github.com/cholalabs/passport-localapikey/issues/13

Please use `passport-localapikey-update` so we can proceed.

Thanks for the contribution 👍

**Comment by isayme** [comment]
@poeti8 would you mind if I would prefer to use `passport-apikey` ?  it's another fork but with a better package name. 

passport-localapikey-update@0.6.0 and passport-apikey@0.0.5 have no additional feature beyond passport-localapikey@0.0.4

**Comment by isayme** [comment]
https://github.com/maisquestoes/passport-apikey

**Comment by poeti8** [comment]
@isayme Name is not important in my opinion. `passport-localapikey-update` is more well known and its last commit was 2017 while `passport-apikey`'s was 2015. There's no `passport-localapikey@0.0.4` on NPM so we have to use one of these new forks. (Or just install from GitHub repo)

**Comment by isayme** [comment]
@poeti8 done with `passport-localapikey-update`

**Pull request merged**
