### PR TITLE
Automatic multiplatform Docker images via GitHub Actions

### PR DESCRIPTION
**Pull request by xescure**
**What the code does**

- As requested in #429 this code creates images that also function on armv7 hardware (incl. Raspberry Pis).
- With every new GitHub release a container is compiled and pushed to `kutt/kutt:<release version>` and `kutt/kutt:latest` on DockerHub.
- The current code in the `develop` branch is compiled and pushed to `kutt/kutt:develop`.
- The current README file in the `develop` branch is synced to the description of the DockerHub repository.

**Todos before application**

1. Disable autobuild on DockerHub (if enabled)
2. Change the repository's Actions secrets:
- DOCKERHUB_USERNAME to the Docker Hub username
- DOCKERHUB_PASSWORD to the Docker Hub password
- DOCKERHUB_TOKEN to a Docker Hub user [token](https://hub.docker.com/settings/security) (does not work with 2FA enabled)
3. Test compiled containers.

### CODE REVIEW

**Comment by poeti8** [comment]
@xescure I get this error, any idea why? (I have set all 3 secrets on GitHub settings)

image

**Comment by xescure** [comment]
@poeti8 I went over a few possibilities, but none of them result in the credentials not getting passed to the task. Even if the username or the token are incorrect the logs should still look something like this:

image


Can you please double check if the Actions secrets are set exactly like this?

image

**Comment by poeti8** [comment]
@xescure nevermind, I was settings environment secrets 🤦

**Comment by xescure** [comment]
@poeti8 I've made it so that the latest changes are only pushed to the `develop` tag, but not to `latest`. And the latter gets updated only when a new version is released. However since that the `latest` image had been manually updated and is still not arm compatible.

Could you make a minor release like `v2.7.2` so everything gets updated?

**Pull request merged**
