### PR TITLE
added dark mode feature with prefers-color-scheme

### PR DESCRIPTION
**Pull request by thetaungg**
I used css-variables for this; I hope that's all right. This pull request adds dark-mode #403

### CODE REVIEW

**Comment by thetaungg** [comment]
I also have a plan to add a switch that watches both prefers-color-scheme and user toggle. It'll be a global switch, not related to the  user account. If this PR is approved, I'll work on that feature.

**Comment by Saleh56** [comment]
S

**Comment by poeti8** [comment]
Thank you for the effort, I'd suggest some improvements:
* Use white (`#f5f5f5`) for texts, titles and logo.
* Use the color from table links for other links such as menu
* Inputs and buttons can have shades of dark blue or black instead of gray-ish colors.
* Update shadows to match dark theme instead of white theme

**Comment by thetaungg** [comment]
ok, @poeti8 . I'll add those improvements. If you don't mind, can you give me some pointers about the switch as well?

**Comment by thetaungg** [comment]
@poeti8 I've updated the code based on your feedback.If you see an more issues, please, don't hesitate to tell me :) .

**Comment by poeti8** [comment]
Thank you, a few more notes:

* Inputs and table buttons should be dark blue/navy. Something like `#21222b`. Also make sure shadows match the color everywhere.
* Neutralize texts, white texts to be less white (bright) so they don't feel like they are glowing on the page
* Error and success messages to keep being red and green (with saturation and brightness that matches the best to background)
* Copy icon on the shortened link has white background and doesn't match the ones on the table
* Browser extension section can have black background (#000) and dark blue buttons
* Dividers on settings page and footer are still white/bright

**Comment by thetaungg** [comment]
Thanks for the feedback, I'll fix those right away.

**Comment by thetaungg** [comment]
@poeti8 I've updated the code. Please take a look.

**Comment by poeti8** [comment]
* login form error is still white
* This text `A verification email has been sent to [email].`, email address color is too dark.
* On the charts the gray bar can be more fade and transparent and the tooltip/legend can have a white background. And texts on the axios like windows. android, etc can be brighter

image

Thanks

**Comment by thetaungg** [comment]
It's my own recklessness.Thank you for checking it thoroughly.
I'll check the code more carefully before the next commit.

**Comment by poeti8** [comment]
No problem mate, thanks for the effort. 
By the way, just checked again, red for errors is still a bit too dark.

**Comment by thetaungg** [comment]
Noted :)

**Comment by thetaungg** [comment]
I've updated the code. I had to install `@types/recharts` library for the type definition of   `recharts` in order to make my life easier in modifying the styles of the charts; I hope that's okay.

**Comment by thetaungg** [comment]
I can't believe I didn't see this issue. I'm really sorry.

**Comment by poeti8** [comment]
I was thinking on what if we use a theme library for styled-components or write a custom one instead of using css variables. 🤔

**Comment by thetaungg** [comment]
I like theme library but I think using css variables is more popular(I believe it's the future). And it's also faster because I can simply add a toggle theme button which will simply toggle a classname.

**Comment by thetaungg** [comment]
Nevertheless, if you still like to switch over styled-components theme, I'd be happy to make the adjustments.

**Comment by thetaungg** [comment]
@poeti8 What is your decision?

**Comment by poeti8** [comment]
Sorry for the late reply. I am thinking on using themes in a CSS-in-JS approach. [theme-ui](https://theme-ui.com/getting-started) is a good one and it goes well with Rebass. We can even switch to [emotion](https://emotion.sh/docs/introduction).

**Comment by thetaungg** [comment]
If we use theme-ui, there'll be 2 CSS-in-JS libraries in our codebase, and if we use emotion we'll have to refactor almost every component in our codebase. Personally, either option doesn't sound pleasant to me compared to this 400-line-addition pull request. But if that what you want you can close this pull request.

**Pull request closed without merging**
