### PR TITLE
[fix] Migrations

### PR DESCRIPTION
**Pull request by marvin-wtt**
#### Description:

This PR restructures the migration process to avoid issues where migrations were updated after they’ve already been applied. Updating migrations late leads to failures when running clean migrations, breaking database consistency.

#### Changes:

- Moved existing migrations from the `models` directory to a dedicated `migrations` directory.
- Removed duplicate migrations and existence checks

#### Note:

This PR is based of #762

### CODE REVIEW

**Comment by poeti8** [comment]
See this commit, this fixes the issue where knex was looking for the previous `.ts` files to verify the migration: https://github.com/thedevs-network/kutt/commit/9d9f57abae56a09f142efa6b023c1246c6b8dfed

But regarding the migration files, this is how I see them: Keep the current migration files intact. Create new migration files for all the changes you want to make. Edit the models if necessary, this way it's clear what the final form of a model is by looking at that model file. The changes to the models are only applied when Kutt is running for the first time, otherwise, the changes are ignored and applied through the migration files.

**Comment by marvin-wtt** [comment]
> But regarding the migration files, this is how I see them: Keep the current migration files intact. Create new migration files for all the changes you want to make. Edit the models if necessary, this way it's clear what the final form of a model is by looking at that model file. The changes to the models are only applied when Kutt is running for the first time, otherwise, the changes are ignored and applied through the migration files.

The migration files that were already run should never be executed again by knex. Only new migrations are being executed. All successful migrations are stored in the DB. What I did is revert the migration files to the state before they were applied. All changes were then kept in their respective migration files without the checks, as they are not needed. Just keeping it like this is very bad practice and cause trouble with fresh installations as the migrations are not sequentially. For all existing installations, the changes have no effect as the migrations won't be run again.

**Comment by marvin-wtt** [comment]
> See this commit, this fixes the issue where knex was looking for the previous `.ts` files to verify the migration: [9d9f57a](https://github.com/thedevs-network/kutt/commit/9d9f57abae56a09f142efa6b023c1246c6b8dfed)

Are you sure that this is enough? I think all existing migrations are still considered "new" by knex as the file extension is stored in the migrations table too.

As already mentioned, I don't see any benefits of dropping TS, but it causes trouble like this. I can offer to create a PR and revert the latest v3 back to TS and rebase the PRs, but that's of course your decision.

**Comment by poeti8** [comment]
> Are you sure that this is enough? I think all existing migrations are still considered "new" by knex as the file extension is stored in the migrations table too.

Yes, because the migrations mostly check if the changes are already done or not. For example they only create tables if they have not already been created.

>As already mentioned, I don't see any benefits of dropping TS, but it causes trouble like this. I can offer to create a PR and revert the latest v3 back to TS and rebase the PRs, but that's of course your decision.

No, I still prefer no TypeScript for now.

**Comment by poeti8** [comment]
Closing this for #762

**Pull request closed without merging**
