### PR TITLE
Adding docker compose configuration

### PR DESCRIPTION
**Pull request by guglielmino**
I added a docker compose configuration and changed a bit how server side configuration is handled.  Dumping env vars in `config.js` file at build time can be fine for client side code, in server it's easier to directly access to them.

### CODE REVIEW

**Comment by poeti8** [comment]
@guglielmino Thanks for the PR. I made a PR (#181) to remove config files and use env vars in the app. Please adjust your PR to match the changes.

**Comment by guglielmino** [comment]
@poeti8 it doesn't seem to me a good idea to remove the config.js, it works as a wrapper on environments variables and it's fine, it is useful to keep control on config variables. Are you sure you want to spread all around the code the `process.env.SOMETHING` approach?

**Comment by poeti8** [comment]
Yes, the 2 config files was a bit confusing and if we're going to use env variables why bother with config files. I didn't find them that much useful in this project.

**Comment by guglielmino** [comment]
> Yes, the 2 config files was a bit confusing and if we're going to use env variables why bother with config files. I didn't find them that much useful in this project.

Got it, to be specific I was referring to the server `config.js` only. IMHO having a wrapper let you manage future changes with less effort. Suppose you wan to encrypt values, without the wrapper you need to apply changes all around the code.

**Comment by poeti8** [comment]
> Got it, to be specific I was referring to the server config.js only. IMHO having a wrapper let you manage future changes with less effort. Suppose you wan to encrypt values, without the wrapper you need to apply changes all around the code.

I think it's ok for now. If I see that it's needed I will add a file as a wrapper, not a config file that users should edit directly. 

Regarding this PR, I was also wondering if it's a good idea to publish Kutt on docker hub. I don't have a much experience with docker. Could use some help here.

**Comment by guglielmino** [comment]
Yes, I'm quite expert with Docker and I managed some projects with Travis CI creating and pushing the image on docker hub. Of course, you need an account on Docker cloud, then I can help you to setup the pipeline.

**Comment by poeti8** [comment]
> Yes, I'm quite expert with Docker and I managed some projects with Travis CI creating and pushing the image on docker hub. Of course, you need an account on Docker cloud, then I can help you to setup the pipeline.

That's great. We can discuss more after this PR gets updated and merged.

**Comment by guglielmino** [comment]
Hi, I have been very busy in this days, everything should be fine now, waiting for your feedback.

**Comment by poeti8** [comment]
Since we have .env now, we can remove kutt.env and the config file

**Pull request closed without merging**
