### PR TITLE
Adding dockerization

### LINKED ISSUE #4: Dockerised version
Nice job!
It would be great if you can provide some docker based version of kutt.
It would be awesome if domain can be set just by changing some env variable :)

### PR DESCRIPTION
**Pull request by ebauman**
This PR adds a Dockerfile, based on nodejs-alpine, for running Kutt inside a docker container.

It also adds a docker-examples directory which includes a sample configuration file for kutt server, as well as a README.md explaining how to get up and running. 

This will resolve #4

### CODE REVIEW

**Comment by poeti8** [comment]
Awesome, I think you missed client/config.js in readme though. 

Also, I just realized I can use environment variables on the client side as well (Thanks to Next.js and Webpack). So what about I just use env variables instead of config files? Wouldn't it be easier to use? If so, you can simply add one more commit to edit stuff after I'm done.

**Comment by ebauman** [comment]
Re: client/config.js
There were no modifications to that file necessary to make the dockerization work, so I left it out. It still needs to be part of the standard kutt setup, though. 

Re: only using env variables. I would keep your configuration files how you have them now, but add a commented-out line for what to do in order to use the environment variables.
e.g.
```
# Uncomment if you would prefer to define variable via your environment
# RECAPTCHA_SITE_KEY: process.env.KUTT_RECAPTCHA_SITE_KEY,
RECAPTHA_SITE_KEY: '',
```

That way the end-users are aware they can use env variables if they wish. IMO the default behavior for most would be to just type things into the configuration files. So leaving that as the default may make things easier for them.

**Comment by poeti8** [comment]
@ebauman Awesome, just one more important thing. I just added a new config option, which is really important, because the website was down due to malware links problem. Add it to example config and then we're ready to publish.

Thanks!

**Comment by ebauman** [comment]
I think that should do it!

**Pull request merged**
